bookstore/urls.py
from django.urls import path

from .views import (
    author_detail,
    author_list,
    book_detail,
    book_list,
    bookstore_home,
    contact_us,
    publisher_detail,
    publisher_list,
    store_detail,
    store_list,
)


app_name = "bookstore"
urlpatterns = [
    path("", bookstore_home, name="bookstore_home"),
    path("contact-us", contact_us, name="contact"),
    path("authors", author_list, name="authors_list"),
    path("author/<int:pk>", author_detail, name="author"),
    path("publishers", publisher_list, name="publishers"),
    path("publisher/<int:pk>", publisher_detail, name="publisher"),
    path("books", book_list, name="books"),
    path("book/<int:pk>", book_detail, name="book"),
    path("stores", store_list, name="stores"),
    path("store/<int:pk>", store_detail, name="store"),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("triangle/", include("triangle.urls")),
    path("bookstore/", include("bookstore.urls")),
    path("__debug__/", include("debug_toolbar.urls"), name="render_panel"),
]

triangle/urls.py
from django.urls import path

from .views import create_person, delete_person, find_hypotenuse, list_persons_view, person_detail_view, update_person

urlpatterns = [
    path("", find_hypotenuse, name="find_hypotenuse"),
    path("person/", create_person, name="person"),
    path("person/<int:pk>", update_person, name="update_person"),
    path("persons-list", list_persons_view, name="list_persons"),
    path("person-detail/<int:pk>", person_detail_view, name="person-detail"),
    path("delete-person/<int:pk>", delete_person, name="delete-person"),
]

bookstore/models.py
from django.db import models
from django.db.models import UniqueConstraint


class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    objects = models.Manager()

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=300)

    objects = models.Manager()

    def __str__(self):
        return self.name


class Book(models.Model):
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, null=True)
    authors = models.ManyToManyField(Author, through="BookAuthor")
    name = models.CharField(max_length=300)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    pubdate = models.DateField()
    objects = models.Manager()

    class Meta:
        ordering = ["rating", "price"]

    def __str__(self):
        return self.name


class Store(models.Model):
    books = models.ManyToManyField(Book, through="StoreBook")
    name = models.CharField(max_length=300)

    objects = models.Manager()

    def __str__(self):
        return self.name


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    objects = models.Manager()

    class Meta:
        UniqueConstraint(fields=["book", "author"], name="unique_book_author")

    def __str__(self):
        return f"{self.book} {self.author}"


class StoreBook(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    objects = models.Manager()

    class Meta:
        UniqueConstraint(fields=["store", "book"], name="unique_store_book")

    def __str__(self):
        return f"{self.store} {self.book}"

bookstore/forms.py
from bookstore.tasks import email_sender_task

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils import dateformat, timezone


class ContactForm(forms.Form):
    mail = forms.EmailField(max_length=200, required=True, widget=forms.EmailInput())
    date = forms.DateTimeField(
        input_formats="Y-m-d H:i:s",
        help_text="Date and time (YYYY-MM-DD HH:MM:SS) you would like to receive the notification",
    )
    message = forms.CharField(max_length=500, required=True, widget=forms.Textarea(attrs={"rows": 3}))

    def clean_date(self):
        send_date = self.cleaned_data.get("date")
        if send_date > timezone.now() + timezone.timedelta(days=2):
            raise ValidationError(
                f"Shouldn't be later than 2 days, current UTC time {dateformat.format(timezone.now(), 'Y-m-d H:i:s')}"
            )
        if send_date < timezone.now():
            raise ValidationError(
                f"Can't be in the past. Check UTC current time {dateformat.format(timezone.now(), 'Y-m-d H:i:s')}"
            )
        return self.cleaned_data.get("date")

    def send_email(self):
        recipient = self.cleaned_data.get("mail")
        subject = "celery task"
        text = self.cleaned_data.get("message")
        from_email = settings.EMAIL
        email_sender_task.apply_async(
            (
                subject,
                text,
                from_email,
                recipient,
            ),
            eta=self.cleaned_data.get("date"),
        )

bookstore/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import ContactForm
from .models import Author, Book, Publisher, Store


def bookstore_home(request):
    return render(request, "bookstore_home.html")


def author_list(request):
    authors = Author.objects.order_by("-age").prefetch_related("book_set").annotate(num_book=Count("book"))
    paginator = Paginator(authors, 20)
    page_number = request.GET.get("page")
    objs = paginator.get_page(page_number)
    return render(request, "authors_list.html", {"page_obj": objs})


def author_detail(request, pk):
    obj = get_object_or_404(Author.objects.prefetch_related("book_set").annotate(n_books=Count("book")), pk=pk)
    return render(request, "author_detail.html", {"obj": obj})


def publisher_list(request):
    publishers = (
        Publisher.objects.annotate(num_book=Count("book", distinct=True)).prefetch_related("book_set").order_by("name")
    )
    paginator = Paginator(publishers, 25)
    page_number = request.GET.get("page")
    objs = paginator.get_page(page_number)
    num_pub = publishers.aggregate(num_pub=Count("name"))
    return render(request, "publishers_list.html", {"page_obj": objs, "num_pub": num_pub})


def publisher_detail(request, pk):
    obj = get_object_or_404(
        Publisher.objects.prefetch_related("book_set", "book_set__authors").annotate(
            num_book=Count("book", distinct=True), num_auth=Count("book__authors", distinct=True)
        ),
        pk=pk,
    )
    return render(request, "publisher_detail.html", {"obj": obj})


def book_list(request):
    books = (
        Book.objects.order_by("-rating", "-pubdate")
        .select_related("publisher")
        .prefetch_related("authors")
        .annotate(n_auth=Count("authors", distinct=True))
    )
    paginator = Paginator(books, 25)
    page_number = request.GET.get("page")
    objs = paginator.get_page(page_number)
    num = books.aggregate(books=Count("name"))

    return render(request, "books_list.html", {"page_obj": objs, "num": num})


def book_detail(request, pk):
    obj = get_object_or_404(
        Book.objects.prefetch_related("store_set", "authors")
        .annotate(n_authors=Count("authors", distinct=True), n_stores=Count("store", distinct=True))
        .select_related("publisher"),
        pk=pk,
    )
    return render(request, "book_detail.html", {"obj": obj})


def store_list(request):
    stores = Store.objects.prefetch_related("books").annotate(n_books=Count("books")).order_by("-n_books")
    paginator = Paginator(stores, 30)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "stores_list.html", {"page_obj": page_obj, "total": stores.count()})


def store_detail(request, pk):
    obj = get_object_or_404(
        Store.objects.prefetch_related("books")
        .annotate(n_books=Count("books", distinct=True))
        .order_by("-books__rating", "name"),
        pk=pk,
    )
    return render(request, "store_detail.html", {"obj": obj})


def contact_us(request):
    form = ContactForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.send_email()
            return redirect(reverse("bookstore:bookstore_home"))
    return render(request, "contact.html", {"form": form})

bookstore/templates/author_detail.html
{% extends "base.html" %}
{% block title %}Author Details{% endblock title %}
{% block content %}
<h1>{{ obj.name }}</h1>
<p>Age: {{ obj.age }}</p>
<p>Books({{ obj.n_books }}):<br>
        {% if obj.book_set.all %}
            {% for book in obj.book_set.all %}
            | <a href="{% url 'bookstore:book' book.pk%}">{{ book.name }}</a> |<br>

            {% endfor %}
        {% else %}
        No books
        {% endif %}
    </p>

{% endblock content %}

bookstore/templates/authors_list.html
{% extends "base.html" %}
{% block title %}Authors List{% endblock title %}
{% block content %}
<h1>Authors List</h1>

{% for obj in page_obj %}
<h3>Author</h3>
   <p>Name: {{ obj.name }}</p>
   <p>Age: {{ obj.age }}</p>

    <p>
        Books({{ obj.num_book }}):<br>

    </p>


    <a href="{% url 'bookstore:author' obj.pk%}">Details</a>
<hr>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

bookstore/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bookstores Home Page{% endblock title %}</title>

</head>
<body>
<p>
    <a href="{% url 'bookstore:bookstore_home' %}">Home</a>
    <a href="{% url 'bookstore:authors_list' %}">Authors</a>
    <a href="{% url 'bookstore:publishers' %}">Publishers</a>
    <a href="{% url 'bookstore:books' %}">Books</a>
    <a href="{% url 'bookstore:stores' %}">Stores</a>
    <a href="{% url 'bookstore:contact' %}">Contact Us</a>
</p>


{% block content %}
{% endblock content %}


</body>
</html>

bookstore/templates/book_detail.html
{% extends "base.html" %}
{% block title %}Book detail{% endblock title %}
{% block content %}
<h1>{{ obj.name }}</h1>

<p>Number of pages: {{ obj.pages }}</p>
<p>Price: {{ obj.price }}</p>
<p>Rating: {{ obj.rating }}</p>
<p>Publication date: {{ obj.pubdate }}</p>
<p>Being sold in {{ obj.n_stores }} stores: </p>
    {% for store in obj.store_set.all %}
        | <a href="{% url 'bookstore:store' store.pk %}">{{ store.name }}</a> |

    {% endfor %}
<p>
    authors({{ obj.n_authors }}):</p>
    {% if obj.authors %}
        {% for auth in obj.authors.all %}
            |  <a href="{% url 'bookstore:author' auth.pk %}">{{ auth.name }}</a> |

        {% endfor %}
    {% endif %}




{% endblock content %}

bookstore/templates/books_list.html
{% extends "base.html" %}
{% block title %}Authors List{% endblock title %}
{% block content %}
<h1>{{ num.books }} Books List</h1>

{% for obj in page_obj %}
<h3>{{ obj.name }}</h3>
   <p>Pages: {{ obj.pages }}</p>
    <p>Price: {{ obj.price }}</p>
    <p>Rating: {{ obj.rating }}</p>
    <p>Publication date: {{ obj.pubdate }}</p>
    <p>Authors({{ obj.n_auth }})
        {% if not obj.authors.all %}
            Unknown

        {% endif %}
    </p>

    <a href="{% url 'bookstore:book' obj.pk%}">Details</a>
<hr>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

bookstore/templates/bookstore_home.html
{% extends "base.html" %}
{% block title %}Bookstores Home Page{% endblock title %}
{% block content %}
Hello
{% endblock content %}

bookstore/templates/contact.html
{% extends "base.html" %}
{% block title %}Contact Us{% endblock title %}
{% block content %}
<form action="{% url 'bookstore:contact' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>
{% endblock content %}

bookstore/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h5>Hello, {{ recipient }}</h5>
    <p>
        {{ message }}
    </p>
</body>
</html>

bookstore/templates/publisher_detail.html
{% extends "base.html" %}
{% block title %}Publisher Details{% endblock title %}
{% block content %}
<h1>{{ obj.name }}</h1>
 <p>
        Books({{ obj.num_book}}):<br>
        {% if  obj.book_set.all %}
            {% for book in  obj.book_set.all%}
           <h3>{{ book.name }}</h3> <br> authors:
                {% for auth in book.authors.all %}
                          | <a href="{% url 'bookstore:author' auth.pk%}">{{ auth.name }}</a> |

                {% endfor %}
        <hr>
     <br>
            {% endfor %}
        {% else %}
        No books
        {% endif %}
 </p>

<p>
    Authors published({{ obj.num_auth }}):

</p>
{% endblock content %}

bookstore/templates/publishers_list.html
{% extends "base.html" %}
{% block title %}Publishers List{% endblock title %}
{% block content %}
Publishers {{ num_pub.num_pub }} records

{% for obj in page_obj %}
<h3>{{ obj.name }}</h3>
    <p>Books({{ obj.num_book}}):</p>
    <a href="{% url 'bookstore:publisher' obj.pk%}">Details</a>
<hr>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

bookstore/templates/store_detail.html
{% extends "base.html" %}
{% block title %}Store detail{% endblock title %}
{% block content %}
<h1>{{ obj.name }}</h1>
<p>Books in store {{ obj.n_books }}</p>

{% for book in obj.books.all %}
   {{ book.rating }}| <a href="{% url 'bookstore:book' book.pk %} ">{{ book.name }}</a> | pages:{{ book.pages }}
   | price: {{ book.price }}<br>

{% endfor %}
{% endblock content %}

bookstore/templates/stores_list.html
{% extends "base.html" %}
{% block title %}Stores List{% endblock title %}
{% block content %}
<h1>Total Stores {{ total }}</h1>
{% for obj in page_obj %}
    <h3>{{ obj.name }}</h3>
    <p>Books available {{ obj.books.count }}</p>
    <a href="{% url 'bookstore:store' obj.pk %}">View Store</a>
<hr>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}